{{ config(tags = ['core']) }}

WITH CTE_1 AS (
    SELECT R.*
        , V.VEHICLE_ID
        , P.PRIMARYRATINGSTATE
    FROM {{ source("PEAK_POLICY_CONFORMED", "POLICY") }} 
        AS P
    INNER JOIN {{ source("PEAK_POLICY_CONFORMED", "VEHICLE") }} 
        AS V
        ON P.POLICYREADONLYHISTORYID = V.POLICYREADONLYHISTORYID
    INNER JOIN {{ source ("PEAK_POLICY_CONFORMED", "RISK_COVERAGE") }} 
        AS R
        ON V.POLICYREADONLYHISTORYID = R.POLICYREADONLYHISTORYID
        AND V.RISK_ID = R.RISK_ID
    )

SELECT * FROM CTE_1