{{ config(tags = ['core']) }}

WITH CTE_1
AS
(
    SELECT V.*, T.EFFECTIVEDATE as EFFECTIVEDATE 
    FROM {{ source('PEAK_POLICY_CONFORMED', 'VEHICLE_VINSYMBOL') }} 
    AS V 
    INNER JOIN 
    {{ source('PEAK_POLICY_CONFORMED', 'TRANSACTION') }} as T
    ON V.POLICYREADONLYHISTORYID = T.POLICYREADONLYHISTORYID
    AND T.HISTORYID = T.POLICYREADONLYHISTORYID
)

SELECT * FROM CTE_1