{{ config(tags = ['reference']) }}

WITH CTE_1
AS
(
    SELECT 'SAT_RDS_COV_DED_LIT' AS REFERENCE_RULE_TABLE_NAME
    UNION ALL SELECT 'SAT_RDS_COV_LIMIT_LIT' AS REFERENCE_RULE_TABLE_NAME
    UNION ALL SELECT 'SAT_RDS_COV_MNEMONICS' AS REFERENCE_RULE_TABLE_NAME
    UNION ALL SELECT 'SAT_RDS_PRODUCT_RSK_TYP_TBL' AS REFERENCE_RULE_TABLE_NAME
)

SELECT * FROM CTE_1