CREATE TABLE HUB_CUSTOMER
(
	CUSTOMER_HK            BINARY() NOT NULL,
	LOAD_TIMESTAMP       TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	RECORD_SOURCE        VARCHAR(100) NULL,
	CUSTOMER_NO        VARCHAR(50) NULL
);

ALTER TABLE HUB_CUSTOMER
ADD PRIMARY KEY (CUSTOMER_HK);

CREATE TABLE LNK_CUSTOMER_NATION
(
	CUSTOMER_HK            BINARY() NOT NULL,
	LOAD_TIMESTAMP       TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	RECORD_SOURCE        VARCHAR(100) NULL,
	CUSTOMER_NATION_HK BINARY(16) NOT NULL,
	NATION_DETAILS_HK  BINARY(16) NOT NULL
);

ALTER TABLE LNK_CUSTOMER_NATION
ADD PRIMARY KEY (CUSTOMER_NATION_HK);

CREATE TABLE SAT_CUST_NATION_DETAILS
(
	LOAD_TIMESTAMP       TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	RECORD_SOURCE        VARCHAR(100) NULL,
	HASHDIFF             BINARY(16) NULL,
	EFFECTIVE_TIMESTAMP  TIMESTAMP NULL,
	SampleColumn1        DATE NULL,
	SampleColumn2        DATE NULL,
	NATION_DETAILS_HK BINARY(16) NOT NULL
);

ALTER TABLE SAT_CUST_NATION_DETAILS
ADD PRIMARY KEY (LOAD_TIMESTAMP,NATION_DETAILS_HK);

ALTER TABLE LNK_CUSTOMER_NATION
ADD CONSTRAINT R_6 FOREIGN KEY (CUSTOMER_HK) REFERENCES HUB_CUSTOMER (CUSTOMER_HK);

ALTER TABLE SAT_CUST_NATION_DETAILS
ADD CONSTRAINT R_76 FOREIGN KEY (NATION_DETAILS_HK) REFERENCES LNK_CUSTOMER_NATION (NATION_DETAILS_HK);