{{ config(tags = ['core']) }}

WITH CTE_1
AS
(
    SELECT O.*, T.EFFECTIVEDATE AS EFFECTIVEDATE 
    FROM  {{ source('PEAK_POLICY_CONFORMED', 'VEHICLE_REGISTRATIONOWNERSHIP') }} 
    AS O 
    INNER JOIN 
    {{ source('PEAK_POLICY_CONFORMED', 'TRANSACTION') }} 
    AS T
    ON O.POLICYREADONLYHISTORYID = T.POLICYREADONLYHISTORYID
    and T.HISTORYID = T.POLICYREADONLYHISTORYID
)

SELECT * FROM CTE_1