{{ config(tags = ['core']) }}

with CTE_1
as
(
    select U.*, T.EFFECTIVEDATE AS EFFECTIVEDATE 
    from  {{ source('PEAK_POLICY_CONFORMED', 'VEHICLE_USAGEDETAILS') }} 
    as U 
    inner join 
    {{ source('PEAK_POLICY_CONFORMED', 'TRANSACTION') }} 
    AS T
    ON U.POLICYREADONLYHISTORYID = T.POLICYREADONLYHISTORYID
    and T.HISTORYID = T.POLICYREADONLYHISTORYID

)

SELECT * FROM CTE_1