{{ config(tags = ['core']) }}

SELECT POLICYREADONLYHISTORYID AS TRANSACTION_NK FROM {{ source('PEAK_POLICY_CONFORMED', 'TRANSACTION') }}
UNION
SELECT TO_VARCHAR(CAST(HISTORYID AS NUMBER(38,0))) AS TRANSACTION_NK FROM {{ source('PEAK_POLICY_CONFORMED', 'TRANSACTION') }}
UNION
SELECT TO_VARCHAR(CAST(PREVIOUSHISTORYID AS NUMBER(38,0))) AS TRANSACTION_NK FROM {{ source('PEAK_POLICY_CONFORMED', 'TRANSACTION') }}

